/**
 * Fix common English phrases in French detailed explanations.
 * Run: node scripts/fix_fr_english_mix.js
 */
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/data/detailedExplanationsTranslations.ts');
let content = fs.readFileSync(filePath, 'utf-8');

// Replacements: [regex, replacement] - order matters for some
const replacements = [
  // Common English → French in prose (avoid code: def, return, if, for, etc.)
  [/\bReturns:\s/g, 'Retourne : '],
  [/\bResult:\s/g, 'Résultat : '],
  [/\bReturns\s/g, 'Retourne '],
  [/\bResult\s/g, 'Résultat '],
  [/\bWhen you /g, 'Quand vous '],
  [/\bWhen you\b/g, 'Quand vous'],
  [/\bIf you /g, 'Si vous '],
  [/\bThis is /g, 'C\'est '],
  [/\bThis gives /g, 'Cela donne '],
  [/\bThis allows /g, 'Cela permet '],
  [/\bThis permits /g, 'Cela permet '],
  [/\bThis returns /g, 'Cela retourne '],
  [/\bThis contrasts /g, 'Cela contraste '],
  [/\bcan be called\b/g, 'peut être appelé'],
  [/\bcan be passed\b/g, 'peut être passé'],
  [/\bcan be positional\b/g, 'peut être positionnel'],
  [/\bcan be keyword\b/g, 'peut être mot-clé'],
  [/\bcan be converted\b/g, 'peut être converti'],
  [/\bcan be used\b/g, 'peut être utilisé'],
  [/\bcan be iterated\b/g, 'peut être itéré'],
  [/\bis used to\b/g, 'est utilisé pour'],
  [/\bit returns\b/g, 'il retourne'],
  [/\bit creates\b/g, 'il crée'],
  [/\bit finds\b/g, 'il trouve'],
  [/\bthe same as\b/g, 'le même que'],
  [/\bWorks same as\b/g, 'Fonctionne comme'],
  [/\bworks same as\b/g, 'fonctionne comme'],
  [/\bmust be passed\b/g, 'doit être passé'],
  [/\bmust be positional\b/g, 'doit être positionnel'],
  [/\bmust be keyword\b/g, 'doit être mot-clé'],
  [/\b(\w+) is positional-only\b/g, '$1 est positionnel uniquement'],
  [/\b(\w+) is regular\b/g, '$1 est régulier'],
  [/\b(\w+) is keyword-only\b/g, '$1 est mot-clé uniquement'],
  // Bullet points
  [/\• View reflects /g, '• La vue reflète '],
  [/\• Updates automatically /g, '• Se met à jour automatiquement '],
  [/\• Not une liste /g, '• Pas une liste '],
  [/\• Getting keys: /g, '• Obtenir les clés : '],
  [/\• Iterating keys: /g, '• Itérer les clés : '],
  [/\• Key iteration/g, '• Itération des clés'],
  [/\• Dictionary key access/g, '• Accès aux clés du dictionnaire'],
  [/\• Data encapsulation without classes/g, '• Encapsulation de données sans classes'],
  [/\• Creating function factories/g, '• Créer des usines de fonctions'],
  [/\• Maintaining state between calls/g, '• Maintenir l\'état entre les appels'],
  [/\• Creating families of related functions/g, '• Créer des familles de fonctions liées'],
  [/\• Partial application of arguments/g, '• Application partielle des arguments'],
  [/\• Currying patterns/g, '• Patterns de curryfication'],
  [/\• Parameter restrictions/g, '• Restrictions sur les paramètres'],
  [/\• Fine-grained control/g, '• Contrôle granulaire'],
  // doesn't → ne ... pas (context-aware, simple cases)
  [/\bdoesn't work\b/g, 'ne fonctionne pas'],
  [/\bdoesn't exist\b/g, 'n\'existe pas'],
  [/\bdoesn't store\b/g, 'ne stocke pas'],
  [/\bdoesn't receive\b/g, 'ne reçoit pas'],
  [/\bdoesn't get\b/g, 'n\'est pas'],
  [/\bdoesn't trigger\b/g, 'ne déclenche pas'],
  [/\bdoesn't mangle\b/g, 'ne mangle pas'],
  [/\bdoesn't implement\b/g, 'n\'implémente pas'],
  [/\bdoesn't propagate\b/g, 'ne se propage pas'],
  [/\bdoesn't execute\b/g, 'ne s\'exécute pas'],
  [/\bdoesn't include\b/g, 'n\'inclut pas'],
  [/\bdoesn't reach\b/g, 'n\'atteint pas'],
  [/\bdoesn't change\b/g, 'ne change pas'],
  [/\bdoesn't affect\b/g, 'n\'affecte pas'],
  [/\bdoesn't hide\b/g, 'ne masque pas'],
  [/\bdoes nothing\b/g, 'ne fait rien'],
  [/\bdoes not support\b/g, 'ne supporte pas'],
  [/\bdoes not store\b/g, 'ne stocke pas'],
  [/\bdoes not modifier\b/g, 'ne modifie pas'],
  [/\bdoesn't renvoyer\b/g, 'ne renvoie pas'],
  // Positional/keyword - fix "is positional-only" etc in bullets
  [/\• x is positional-only \(before/g, '• x est positionnel uniquement (avant'],
  [/\• y is regular \(between/g, '• y est régulier (entre'],
  [/\• z is keyword-only \(after/g, '• z est mot-clé uniquement (après'],
  [/\• Argument 1 is positional/g, '• L\'argument 1 est positionnel'],
  [/\• Argument 2 is positional/g, '• L\'argument 2 est positionnel'],
  [/\• z=3 is keyword argument/g, '• z=3 est un argument mot-clé'],
  [/\• Function executes:/g, '• La fonction s\'exécute :'],
  [/\• func\(1, 2, z=3\) calls function func/g, '• func(1, 2, z=3) appelle la fonction func'],
  [/\• add5 is now/g, '• add5 est maintenant'],
  [/\• f is inner/g, '• f est inner'],
  // Closure/function
  [/\bThe second \(\) calls the returned function\b/g, 'Le second () appelle la fonction retournée'],
  [/\bA closure captures variables from its enclosing scope\b/g, 'Une fermeture capture les variables de sa portée englobante'],
  [/\binner\(\) has no local x\b/g, 'inner() n\'a pas de x local'],
  [/\bit finds x = 10 in outer\(\)'s scope\b/g, 'il trouve x = 10 dans la portée de outer()'],
  [/\bouter\(\) returns a function object\b/g, 'outer() retourne un objet fonction'],
  [/\bnot a value\b/g, 'pas une valeur'],
  [/\breturns inner\b/g, 'retourne inner'],
  [/\breturns a lambda\b/g, 'retourne une lambda'],
  [/\bWhen you call\b/g, 'Quand vous appelez'],
  [/\bit returns a lambda\b/g, 'il retourne une lambda'],
  [/\bwhere n is bound to\b/g, 'où n est lié à'],
  [/\bCalling add5\(3\) executes\b/g, 'Appeler add5(3) exécute'],
  [/\bCalling the returned function\b/g, 'Appeler la fonction retournée'],
  [/\bThe lambda captures\b/g, 'La lambda capture'],
  [/\bfrom make_adder's scope\b/g, 'de la portée de make_adder'],
  [/\bEach call to make_adder creates\b/g, 'Chaque appel à make_adder crée'],
  [/\badd5 = make_adder\(5\) creates\b/g, 'add5 = make_adder(5) crée'],
  [/\bthat always adds 5\b/g, 'qui ajoute toujours 5'],
  [/\bmake_adder\(5\) sets n = 5\b/g, 'make_adder(5) définit n = 5'],
  [/\badd5\(3\) evaluates\b/g, 'add5(3) évalue'],
  // Instead of
  [/\bInstead of checking if a key exists\b/g, 'Au lieu de vérifier si une clé existe'],
  [/\bjust access it and catch\b/g, 'y accéder directement et attraper'],
  [/\bInstead of checking if a file exists\b/g, 'Au lieu de vérifier si un fichier existe'],
  [/\bjust open it and catch\b/g, 'l\'ouvrir directement et attraper'],
  // Common phrases
  [/\bwhen failures are rare\b/g, 'quand les échecs sont rares'],
  [/\bAvoids race conditions\b/g, 'Évite les conditions de concurrence'],
  [/\bstate can change between check and use\b/g, 'l\'état peut changer entre la vérification et l\'utilisation'],
  [/\bwhen an exception occurs\b/g, ' quand une exception se produit'],
  [/\bthe else clause doesn't execute\b/g, 'la clause else ne s\'exécute pas'],
  [/\bso x is never defined\b/g, 'donc x n\'est jamais défini'],
  [/\bwhen you call max\(\)/g, 'quand vous appelez max()'],
  [/\bwhen you call min\(\)/g, 'quand vous appelez min()'],
  [/\bwhen you create\b/g, 'quand vous créez'],
  [/\bwhen you iterate\b/g, 'quand vous itérez'],
  [/\bWhen you iterate\b/g, 'Quand vous itérez'],
  [/\bwhen the dictionary changes\b/g, 'quand le dictionnaire change'],
  [/\bIterates:\s/g, 'Itère : '],
  // don't patterns
  [/\bdon't get name mangled\b/g, 'n\'est pas mangle'],
  [/\bdon't mangle\b/g, 'ne mangle pas'],
  [/\bdon't enforce\b/g, 'n\'applique pas'],
  [/\bdon't receive\b/g, 'ne reçoit pas'],
  [/\bdon't inherit\b/g, 'n\'hérite pas'],
  [/\bParent doesn't inherit\b/g, 'Parent n\'hérite pas'],
  [/\bdon't change\b/g, 'ne change pas'],
  [/\bdon't matter\b/g, 'n\'a pas d\'importance'],
  [/\bdon't run\b/g, 'ne s\'exécute pas'],
  [/\bdon't store\b/g, 'ne stocke pas'],
  [/\bdon't compute\b/g, 'ne calcule pas'],
  [/\bdon't have\b/g, 'n\'a pas'],
  [/\bdon't affect\b/g, 'n\'affecte pas'],
  [/\bdon't need\b/g, 'n\'a pas besoin'],
  [/\bdon't use\b/g, 'n\'utilise pas'],
  [/\bdon't support\b/g, 'ne supporte pas'],
  [/\bdon't allow\b/g, 'ne permet pas'],
  [/\bdon't modify\b/g, 'ne modifie pas'],
  [/\border doesn't matter\b/g, 'l\'ordre n\'a pas d\'importance'],
  [/\bCode doesn't run\b/g, 'Le code ne s\'exécute pas'],
  [/\bIterator doesn't compute\b/g, 'L\'itérateur ne calcule pas'],
  [/\bInstances don't have\b/g, 'Les instances n\'ont pas'],
  [/\btype hints don't affect\b/g, 'les annotations de type n\'affectent pas'],
  [/\btype hints don't enforce\b/g, 'les annotations de type n\'appliquent pas'],
  [/\bClass doesn't need\b/g, 'La classe n\'a pas besoin'],
  [/\bstatic methods don't receive\b/g, 'les méthodes statiques ne reçoivent pas'],
  [/\bstatic methods don't change\b/g, 'les méthodes statiques ne changent pas'],
  [/\blocal variables don't affect\b/g, 'les variables locales n\'affectent pas'],
  [/\bthe container.*doesn't matter\b/g, 'le conteneur n\'a pas d\'importance'],
  [/\bsets don't allow duplicates\b/g, 'les ensembles ne permettent pas les doublons'],
  [/\bclass statement doesn't use\b/g, 'l\'instruction class n\'utilise pas'],
  [/\bclass statement doesn't support\b/g, 'l\'instruction class ne supporte pas'],
  [/\bit retourne\b/g, 'il retourne'],
  [/\bgenerators don't store\b/g, 'les générateurs ne stockent pas'],
  [/\bthey don't compute\b/g, 'ils ne calculent pas'],
  [/\b(integers )?don't have __name__\b/g, 'n\'ont pas __name__'],
  [/\bKeyword arguments don't need\b/g, 'Les arguments nommés n\'ont pas besoin'],
  // Decorator/wrapper prose
  [/\bThis decorator\b/g, 'Ce décorateur'],
  [/\bThe decorator\b/g, 'Le décorateur'],
  [/\bThe wrapper\b/g, 'Le wrapper'],
  [/\bwrapper function\b/g, 'fonction wrapper'],
  [/\bthe original function\b/g, 'la fonction originale'],
  [/\breplaces the original function\b/g, 'remplace la fonction originale'],
  [/\bcalls the original\b/g, 'appelle l\'originale'],
  [/\bwhich calls the original\b/g, 'qui appelle l\'originale'],
  [/\bit actually calls\b/g, 'c\'est en fait'],
  [/\bpreserves the original\b/g, 'préserve l\'originale'],
  [/\ballowing additional logic\b/g, 'permettant une logique supplémentaire'],
  [/Function wrapping decorator:/g, 'Décorateur de wrapping de fonction :'],
  [/\• @decorator replaces func with wrapper\b/g, '• @decorator remplace func par wrapper'],
  [/\• wrapper\(\) calls original func\(\)\b/g, '• wrapper() appelle la fonction originale func()'],
  [/\• func\(\) now calls wrapper\b/g, '• func() appelle maintenant wrapper'],
  [/\• Add behavior without changing\b/g, '• Ajouter du comportement sans modifier'],
  [/\• Logging, timing, validation\b/g, '• Journalisation, chronométrage, validation'],
  [/\• Cross-cutting concerns\b/g, '• Préoccupations transversales'],
  [/\• Reusable wrapper logic\b/g, '• Logique de wrapper réutilisable'],
  [/\bThe decorator wraps the original\b/g, 'Le décorateur enveloppe l\'originale'],
  // Generic prose patterns
  [/\bThis (function|method|operator)\b/g, 'Cette $1'],
  [/\bThis (creates|returns|allows|permits)\b/g, 'Cela $1'],
  [/\bThe (function|method)\b/g, 'La $1'],
  [/\bwhen (the |it )?is called\b/g, 'quand il est appelé'],
  [/\bwhich (calls|returns|creates)\b/g, 'qui $1'],
  [/\bcalls the (original|wrapper)\b/g, 'appelle la $1'],
  [/\b(called|applied) (to|with)\b/g, '$1 $2'],
  [/\bgets (the )?result\b/g, 'obtient le résultat'],
  [/\bgets (\d+)\b/g, 'obtient $1'],
  // Section headers in English
  [/^Generic wrapper with preserved arguments:$/gm, 'Wrapper générique avec arguments préservés :'],
  [/^Function wrapping decorator:$/gm, 'Décorateur de wrapping de fonction :'],
  [/\• Works with any function signature\b/g, '• Fonctionne avec toute signature de fonction'],
  [/\• All arguments passed to original\b/g, '• Tous les arguments sont passés à l\'originale'],
  [/\• decorator\(func\) called\b/g, '• decorator(func) appelé'],
  [/\• func assigned wrapper\b/g, '• func assigné au wrapper'],
  [/\• wrapper calls original add\b/g, '• wrapper appelle l\'originale add'],
  [/\• Add behavior\b/g, '• Ajouter du comportement'],
  // Common bullets
  [/\• Each new block\b/g, '• Chaque nouveau bloc'],
  [/\• Nested blocks indent\b/g, '• Les blocs imbriqués s\'indentent'],
  [/\• Editors should be configured\b/g, '• Les éditeurs doivent être configurés'],
  [/\• Keep code lines within\b/g, '• Garder les lignes de code dans'],
  [/\• Use implicit line continuation\b/g, '• Utiliser la continuation de ligne implicite'],
  [/\• Use backslash for explicit\b/g, '• Utiliser le backslash pour'],
  [/\• Wrap long expressions\b/g, '• Diviser les longues expressions'],
  [/\• Ensures code is readable\b/g, '• Assure que le code est lisible'],
  [/\• Makes side-by-side diff\b/g, '• Facilite les comparaisons côte à côte'],
  [/\• Prevents horizontal scrolling\b/g, '• Évite le défilement horizontal'],
  [/\• All Python source files\b/g, '• Tous les fichiers source Python'],
  [/\• Most editors and IDEs\b/g, '• La plupart des éditeurs et IDE'],
  [/\• Consistent indentation improves\b/g, '• L\'indentation cohérente améliore'],
  [/\• 4 spaces per indentation\b/g, '• 4 espaces par niveau d\'indentation'],
  [/\• Tabs should not be used\b/g, '• Les tabulations ne doivent pas être utilisées'],
  [/\• Python 3 disallows mixing\b/g, '• Python 3 interdit le mélange'],
  [/\• Continuation lines should align\b/g, '• Les lignes de continuation doivent s\'aligner'],
  [/\• 79 characters maximum\b/g, '• 79 caractères maximum'],
  [/\• 72 characters maximum\b/g, '• 72 caractères maximum'],
  [/\• Long lines can be broken\b/g, '• Les longues lignes peuvent être coupées'],
  [/\• Function names use lowercase\b/g, '• Les noms de fonctions utilisent des minuscules'],
  [/\• This improves readability\b/g, '• Cela améliore la lisibilité'],
  [/\• Add behavior without changing function code\b/g, '• Ajouter du comportement sans modifier le code de la fonction'],
  // Prose verb and phrase replacements (avoid code - these match in bullets/paragraphs)
  [/\bwhich returns\b/g, 'qui retourne'],
  [/\bwhich creates\b/g, 'qui crée'],
  [/\bwhich calls\b/g, 'qui appelle'],
  [/\bwhich contains\b/g, 'qui contient'],
  [/\bwhich yields\b/g, 'qui produit'],
  [/\bwhich passes\b/g, 'qui passe'],
  [/\bwhich stores\b/g, 'qui stocke'],
  [/\bwhich collects\b/g, 'qui collecte'],
  [/\bwhich executes\b/g, 'qui exécute'],
  [/\bwhich iterates\b/g, 'qui itère'],
  [/\bwhich receives\b/g, 'qui reçoit'],
  [/\bwhich triggers\b/g, 'qui déclenche'],
  [/\bwhich preserves\b/g, 'qui préserve'],
  [/\bwhich provides\b/g, 'qui fournit'],
  [/\bwhich specifies\b/g, 'qui spécifie'],
  [/\bwhich produces\b/g, 'qui produit'],
  [/\bthat returns\b/g, 'qui retourne'],
  [/\bthat creates\b/g, 'qui crée'],
  [/\bthat contains\b/g, 'qui contient'],
  [/\bthat yields\b/g, 'qui produit'],
  [/\bwhen called\b/g, 'quand appelé'],
  [/\bwhen applied\b/g, 'quand appliqué'],
  [/\bwhen used\b/g, 'quand utilisé'],
  [/\bwhen the function\b/g, 'quand la fonction'],
  [/\bthe function returns\b/g, 'la fonction retourne'],
  [/\bthe function creates\b/g, 'la fonction crée'],
  [/\bthe method returns\b/g, 'la méthode retourne'],
  [/\bthe method creates\b/g, 'la méthode crée'],
  [/\bthe result\b/g, 'le résultat'],
  [/\bthe same\b/g, 'le même'],
  [/\bthe original\b/g, 'l\'originale'],
  [/\bthe wrapper\b/g, 'le wrapper'],
  [/\bis called\b/g, 'est appelé'],
  [/\bis returned\b/g, 'est retourné'],
  [/\bis created\b/g, 'est créé'],
  [/\bis passed\b/g, 'est passé'],
  [/\bis used\b/g, 'est utilisé'],
  [/\bare passed\b/g, 'sont passés'],
  [/\bare collected\b/g, 'sont collectés'],
  [/\bare stored\b/g, 'sont stockés'],
  [/\bhas a\b/g, 'a un'],
  [/\bhas no\b/g, 'n\'a pas'],
  [/\bhave a\b/g, 'ont un'],
  [/\beach element\b/g, 'chaque élément'],
  [/\beach call\b/g, 'chaque appel'],
  [/\beach iteration\b/g, 'chaque itération'],
  [/\bonly when\b/g, 'uniquement quand'],
  [/\bonly if\b/g, 'uniquement si'],
  [/\bonly the\b/g, 'seulement le'],
  [/\bafter the\b/g, 'après le'],
  [/\bbefore the\b/g, 'avant le'],
  [/\bfrom its\b/g, 'de sa'],
  [/\bcreates a\b/g, 'crée un'],
  [/\bcontains the\b/g, 'contient le'],
  [/\bstores the\b/g, 'stocke le'],
  [/\bcollects the\b/g, 'collecte le'],
  [/\bpasses the\b/g, 'passe le'],
  [/\brequires a\b/g, 'requiert un'],
  [/\bprovides a\b/g, 'fournit un'],
  [/\bproduces a\b/g, 'produit un'],
  [/\biterates over\b/g, 'itère sur'],
  [/\biterates through\b/g, 'itère sur'],
  [/\byields the\b/g, 'produit le'],
  [/\bexecutes the\b/g, 'exécute le'],
  [/\btriggers the\b/g, 'déclenche le'],
  [/\bpreserves the\b/g, 'préserve le'],
  [/\bapplied to\b/g, 'appliqué à'],
  [/\bcalled with\b/g, 'appelé avec'],
  [/\bused for\b/g, 'utilisé pour'],
  [/\bused to\b/g, 'utilisé pour'],
  [/\bused in\b/g, 'utilisé dans'],
  [/\bcalled when\b/g, 'appelé quand'],
  [/\bpassed to\b/g, 'passé à'],
  [/\bpassed as\b/g, 'passé comme'],
  [/\breturns the\b/g, 'retourne le'],
  [/\breturns a\b/g, 'retourne un'],
  [/\breturns an\b/g, 'retourne un'],
  [/\breturns None\b/g, 'retourne None'],
  [/\bassigns the\b/g, 'assigne le'],
  [/\bassigns a\b/g, 'assigne un'],
  [/\breceives the\b/g, 'reçoit le'],
  [/\bfinds the\b/g, 'trouve le'],
  [/\bdisplays the\b/g, 'affiche le'],
  [/\bholds the\b/g, 'contient le'],
  [/\bsupports the\b/g, 'supporte le'],
  [/\bspecifies the\b/g, 'spécifie le'],
  [/\bwork with\b/g, 'fonctionner avec'],
  [/\bworks with\b/g, 'fonctionne avec'],
  // More patterns
  [/\bcrée a wrapper that accepts\b/g, 'crée un wrapper qui accepte'],
  [/\bpasses them to la fonction originale\b/g, 'les passe à la fonction originale'],
  [/\bThis permet\b/g, 'Cela permet'],
  [/\bto fonctionner avec functions that have\b/g, 'de fonctionner avec des fonctions ayant'],
  [/\binto tuple\b/g, 'en tuple'],
  [/\binto dict\b/g, 'en dictionnaire'],
  [/\bunchanged\b/g, 'inchangés'],
  [/\bl'originale function\b/g, 'la fonction originale'],
  [/\blevel is the standard\b/g, 'est la norme'],
  [/\bfor indentation\b/g, 'pour l\'indentation'],
  [/\btabs and spaces\b/g, 'tabulations et espaces'],
  [/\bwith the opening delimiter\b/g, 'avec le délimiteur ouvrant'],
  [/\bby 4 spaces\b/g, 'de 4 espaces'],
  [/\bto insert spaces when Tab is pressed\b/g, 'pour insérer des espaces quand Tab est pressé'],
  [/\bshould follow this convention\b/g, 'doivent suivre cette convention'],
  [/\bcan be configured for 4-space indentation\b/g, 'peuvent être configurés pour l\'indentation à 4 espaces'],
  [/\breadability across teams\b/g, 'la lisibilité pour les équipes'],
  [/\bfor code lines\b/g, 'pour les lignes de code'],
  [/\bwith backslash or parentheses\b/g, 'avec un backslash ou des parenthèses'],
  [/\bwith team agreement\b/g, 'avec accord d\'équipe'],
  [/\binside parentheses, brackets, and braces\b/g, 'dans les parenthèses, crochets et accolades'],
  [/\bwhen needed\b/g, 'si nécessaire'],
  [/\bacross multiple lines\b/g, 'sur plusieurs lignes'],
  [/\bthe universally accepted convention\b/g, 'la convention universellement acceptée'],
  [/\bpreserves all arguments and keyword arguments\b/g, 'préserve tous les arguments et arguments nommés'],
  [/\bmaking it a generic decorator template\b/g, 'en faisant un modèle de décorateur générique'],
  [/\bcollects positional arguments\b/g, 'collecte les arguments positionnels'],
  [/\bcollects keyword arguments\b/g, 'collecte les arguments nommés'],
  [/\bindentation level\b/g, 'niveau d\'indentation'],
  [/\b• \*args collects\b/g, '• *args collecte'],
  [/\b• \*\*kwargs collects\b/g, '• **kwargs collecte'],
  [/d'indentation level is the standard/g, 'd\'indentation est la norme'],
  [/\bGarder les lignes de code dans 79 characters\b/g, 'Garder les lignes de code à 79 caractères'],
  [/\b79 characters\b/g, '79 caractères'],
  [/\b72 characters\b/g, '72 caractères'],
  [/\bline continuation when needed\b/g, 'continuation de ligne si nécessaire'],
  [/\bSome teams allow\b/g, 'Certaines équipes permettent'],
  [/\bFor docstrings and comments\b/g, 'Pour les docstrings et commentaires'],
  [/\bthe limit is even stricter\b/g, 'la limite est encore plus stricte'],
  [/\bPython's official style guide\b/g, 'le guide de style officiel de Python'],
  [/\bspecifies that code should use\b/g, 'spécifie que le code doit utiliser'],
  [/\bTabs are discouraged\b/g, 'Les tabulations sont déconseillées'],
  [/\bmixing tabs and spaces is forbidden\b/g, 'le mélange de tabulations et d\'espaces est interdit'],
  [/\bmixing tabulations et espaces\b/g, 'le mélange de tabulations et d\'espaces'],
  [/\baccepte any arguments\b/g, 'accepte tous les arguments'],
  [/\bany signature\b/g, 'toute signature'],
  [/\bretourne generic wrapper\b/g, 'retourne le wrapper générique'],
  [/\badd assigned generic (fonction )?wrapper\b/g, 'add est assignée au wrapper générique'],
  [/\bcalls wrapper\(/g, 'appelle wrapper('],
  [/\bfurther by 4 more spaces\b/g, 'encore de 4 espaces'],
  [/\b\(after if,\b/g, '(après if,'],
  [/\bs'indentent further\b/g, 's\'indentent encore'],
  // More prose
  [/\bThe try block\b/g, 'Le bloc try'],
  [/\bThe except block\b/g, 'Le bloc except'],
  [/\bThe finally block\b/g, 'Le bloc finally'],
  [/\bThe else clause\b/g, 'La clause else'],
  [/\bThe finally clause\b/g, 'La clause finally'],
  [/\bThis ensures\b/g, 'Cela assure'],
  [/\bThis prevents\b/g, 'Cela empêche'],
  [/\bThis makes it perfect\b/g, 'Cela la rend parfaite'],
  [/\bThis pattern\b/g, 'Ce pattern'],
  [/\bThis shows\b/g, 'Cela montre'],
  [/\bThis indicates\b/g, 'Cela indique'],
  [/\bThis eliminates\b/g, 'Cela élimine'],
  [/\bThis saves memory\b/g, 'Cela économise la mémoire'],
  [/\bThis decouples\b/g, 'Cela découple'],
  [/\bThis avoids\b/g, 'Cela évite'],
  [/\bThis enables\b/g, 'Cela permet'],
  [/\bThis helps prevent\b/g, 'Cela aide à éviter'],
  [/\bYou can access\b/g, 'Vous pouvez accéder'],
  [/\bqui itère over keys\b/g, 'qui itère sur les clés'],
  [/\bthe maximum key\b/g, 'la clé maximale'],
  [/\bthe minimum key\b/g, 'la clé minimale'],
  [/\bthe maximum value\b/g, 'la valeur maximale'],
  [/\bnot the maximum value\b/g, 'pas la valeur maximale'],
  [/\bKeys are compared\b/g, 'Les clés sont comparées'],
  [/\bThe assignment\b/g, 'L\'assignation'],
  [/\bcalls the setter\b/g, 'appelle le setter'],
  [/\bthe setter ignores\b/g, 'le setter ignore'],
  [/\bThe getter still\b/g, 'Le getter'],
  [/\bcalls the deleter\b/g, 'appelle le deleter'],
  [/\bcalls the parent's __init__\b/g, 'appelle le __init__ du parent'],
  [/\bwhich sets\b/g, 'qui définit'],
  [/\bwhich deletes\b/g, 'qui supprime'],
  [/\bexecution immediately jumps\b/g, 'l\'exécution saute immédiatement'],
  [/\bexecution jumps directly\b/g, 'l\'exécution saute directement'],
  [/\bThe Prototype pattern\b/g, 'Le pattern Prototype'],
  [/\bThe Command pattern\b/g, 'Le pattern Command'],
  [/\bThe Composite pattern\b/g, 'Le pattern Composite'],
  [/\bThe Invoker stores\b/g, 'L\'Invoker stocke'],
  [/\bquand needed\b/g, 'quand nécessaire'],
  [/\bfrom the actual operation\b/g, 'de l\'opération réelle'],
  [/\bautomatically generates\b/g, 'génère automatiquement'],
  [/\bbased on class attributes\b/g, 'basé sur les attributs de la classe'],
  [/\bbased on the class attributes\b/g, 'basé sur les attributs de la classe'],
  [/\bonly permits\b/g, 'ne permet que'],
  [/\bAny attempt to set\b/g, 'Toute tentative de définir'],
  [/\bnot in __slots__\b/g, 'absent de __slots__'],
  [/\bby preventing the creation\b/g, 'en évitant la création'],
  [/\bmaking them more concise\b/g, 'les rendant plus concis'],
  // __missing__, defaultdict, dict patterns
  [/\bappelé quand a key is not found\b/g, 'appelée quand une clé n\'est pas trouvée'],
  [/\bC'est exactly how\b/g, 'C\'est exactement ainsi que'],
  [/\bworks internally\b/g, 'fonctionne en interne'],
  [/\bwhen dict\[key\] raises KeyError\b/g, 'quand dict[key] lève KeyError'],
  [/\bIt can set a default and return it\b/g, 'Elle peut définir une valeur par défaut et la retourner'],
  [/\bis equivalent to\b/g, 'est équivalent à'],
  [/\btriggers __missing__\b/g, 'déclenche __missing__'],
  [/\band returns 0\b/g, 'et retourne 0'],
  [/\bexpands to\b/g, 'se développe en'],
  [/\bfails \(key missing\)\b/g, 'échoue (clé absente)'],
  [/\bcalls __missing__\b/g, 'appelle __missing__'],
  [/\bsets self\[/g, 'définit self['],
  [/\bis now (\d+)\b/g, 'vaut maintenant $1'],
  [/\bsets and returns\b/g, 'définit et retourne'],
  [/\bImplementing default values for missing keys\b/g, 'Implémenter des valeurs par défaut pour les clés manquantes'],
  [/\bAuto-initializing counters, lists, or nested dicts\b/g, 'Auto-initialiser des compteurs, listes ou dictionnaires imbriqués'],
  [/\bfor missing keys\b/g, 'pour les clés manquantes'],
  // __new__, __init__, immutable
  [/\best appelé BEFORE __init__\b/g, 'est appelé AVANT __init__'],
  [/\bcrée the object\b/g, 'crée l\'objet'],
  [/\bFor immutable types\b/g, 'Pour les types immuables'],
  [/\bthe value is fixed at creation\b/g, 'la valeur est fixée à la création'],
  [/\bcrée un str with\b/g, 'crée un str avec'],
  [/\bcannot modify an already-created\b/g, 'ne peut pas modifier un objet déjà créé'],
  [/\bcalls UpperStr\.__new__\b/g, 'appelle UpperStr.__new__'],
  [/\bcreates str with value\b/g, 'crée un str avec la valeur'],
  [/\bThe returned object is\b/g, 'L\'objet retourné est'],
  [/\bwith value "HELLO"\b/g, 'avec la valeur "HELLO"'],
  [/\bNormalizing immutable values\b/g, 'Normaliser les valeurs immuables'],
  [/\bat creation time\b/g, 'à la création'],
  [/\bValidating immutable data\b/g, 'Valider les données immuables'],
  [/\bbefore object creation\b/g, 'avant la création de l\'objet'],
  [/\bCreating constrained immutable subtypes\b/g, 'Créer des sous-types immuables contraints'],
  [/\bcreates and retourne un new instance\b/g, 'crée et retourne une nouvelle instance'],
  [/\bthis is where the value is set\b/g, 'c\'est là que la valeur est définie'],
  [/\binitializes an already-created instance\b/g, 'initialise une instance déjà créée'],
  [/\btoo late for immutables\b/g, 'trop tard pour les immutables'],
  [/\bcannot be modified after creation\b/g, 'ne peuvent pas être modifiés après création'],
  [/\bcan be modified in __init__\b/g, 'peuvent être modifiés dans __init__'],
  [/\bbecause their contents are changeable\b/g, 'car leur contenu est modifiable'],
  [/\bcreates the string object\b/g, 'crée l\'objet chaîne'],
  [/\bvalue is now FIXED\b/g, 'la valeur est maintenant FIXÉE'],
  [/\bPython calls\b/g, 'Python appelle'],
  // Common phrases
  [/\bwhen a key is not found\b/g, 'quand une clé n\'est pas trouvée'],
  [/\bduring __getitem__ lookup\b/g, 'lors d\'une recherche __getitem__'],
  [/\bFirst d\["x"\] triggers\b/g, 'Le premier accès à d["x"] déclenche'],
  [/\bquand dict\[key\] raises\b/g, 'quand dict[key] lève'],
  [/\bqui définit d\["x"\] = 0 and returns 0\b/g, 'qui définit d["x"] = 0 et retourne 0'],
  [/\bkey missing\b/g, 'clé absente'],
  [/\b→ calls\b/g, '→ appelle'],
  [/\bsets self\["x"\] = 0 and returns\b/g, 'définit self["x"] = 0 et retourne'],
  [/\b\(__missing__ sets and returns 0\)\b/g, '(__missing__ définit et retourne 0)'],
  [/\b\(__missing__ returns 0, then\b/g, '(__missing__ retourne 0, puis'],
  [/\bBy the time __init__ runs\b/g, 'Au moment où __init__ s\'exécute'],
  [/\bthe immutable value is already set\b/g, 'la valeur immuable est déjà définie'],
  [/\band cannot be changed\b/g, 'et ne peut pas être modifiée'],
  [/\b__init__ cannot modify\b/g, '__init__ ne peut pas modifier'],
  [/\bThe object creation protocol\b/g, 'Le protocole de création d\'objets'],
  [/\bhas two phases\b/g, 'a deux phases'],
  [/\b\(creation\) and __init__ \(initialization\)\b/g, '(création) et __init__ (initialisation)'],
  [/\bFor immutable types, the value is permanently set\b/g, 'Pour les types immuables, la valeur est définitivement fixée'],
  [/\bduring __new__\b/g, 'pendant __new__'],
  [/\bImmutable types \(str, int\b/g, 'Les types immuables (str, int)'],
  [/\bMutable types \(list, dict, set\)\b/g, 'Les types mutables (list, dict, set)'],
  [/\bobj = MyStr\b/g, 'obj = MyStr'],
  [/\bPython calls MyStr\.__new__\b/g, 'Python appelle MyStr.__new__'],
  // More common
  [/\blike str, int, tuple\b/g, 'comme str, int, tuple'],
  [/\byou must override\b/g, 'vous devez surcharger'],
  [/\binstead of __init__\b/g, 'au lieu de __init__'],
  [/\bto customize the value\b/g, 'pour personnaliser la valeur'],
  [/\bin __new__\b/g, 'dans __new__'],
  [/\bthe uppercased value\b/g, 'la valeur en majuscules'],
  [/\ban UpperStr instance with value\b/g, 'une instance UpperStr avec la valeur'],
  [/\bin Python\b/g, 'en Python'],
  [/\b\(creation\) and __init__ \(initialization\)\b/g, '(création) et __init__ (initialisation)'],
  [/\bthe value is permanently set\b/g, 'la valeur est définitivement fixée'],
  [/\bwith its value\b/g, 'avec sa valeur'],
  [/\bPython then calls\b/g, 'Python appelle ensuite'],
  [/\bcannot change the string value\b/g, 'ne peut pas modifier la valeur de la chaîne'],
  [/\bit's immutable\b/g, 'elle est immuable'],
  [/\bToo late!\b/g, 'Trop tard !'],
  [/\bValue is already\b/g, 'La valeur est déjà'],
  [/\bCorrect! Sets value to\b/g, 'Correct ! Définit la valeur à'],
  [/\bC'est why\b/g, 'C\'est pourquoi'],
  [/\bsubclasses must use\b/g, 'les sous-classes doivent utiliser'],
  [/\bfor value customization\b/g, 'pour personnaliser la valeur'],
  [/\bThe 'in' operator calls\b/g, 'L\'opérateur « in » appelle'],
  [/\bBy overriding it\b/g, 'En le surchargeant'],
  [/\byou can customize\b/g, 'vous pouvez personnaliser'],
  [/\bmembership testing behavior\b/g, 'le comportement du test d\'appartenance'],
  [/\bwhile still delegating to\b/g, 'tout en déléguant à'],
  [/\bthe parent implementation\b/g, 'l\'implémentation du parent'],
  [/\bcalls obj\.__contains__\b/g, 'appelle obj.__contains__'],
  [/\bcalls set's original __contains__\b/g, 'appelle le __contains__ original de set'],
  [/\bThe override here adds\b/g, 'La surcharge ici n\'ajoute'],
  [/\bno new behavior but demonstrates\b/g, 'pas de nouveau comportement mais démontre'],
  [/\bthe hook\b/g, 'le point d\'accroche'],
  [/\bYou could add\b/g, 'Vous pourriez ajouter'],
  [/\bbefore\/après le check\b/g, 'avant/après la vérification'],
  [/\bcalls MySet\.__contains__\b/g, 'appelle MySet.__contains__'],
  [/\bThe override calls\b/g, 'La surcharge appelle'],
  [/\b1 is in \{1, 2, 3\}\b/g, '1 est dans {1, 2, 3}'],
  // Context manager, with, __enter__, __exit__
  [/\bThe context manager instance is available\b/g, 'L\'instance du gestionnaire de contexte est disponible'],
  [/\bin the with block through the variable assigned\b/g, 'dans le bloc with via la variable assignée'],
  [/\bTo create a custom context manager\b/g, 'Pour créer un gestionnaire de contexte personnalisé'],
  [/\bTo créer a custom context manager\b/g, 'Pour créer un gestionnaire de contexte personnalisé'],
  [/\ba class must implement both\b/g, 'une classe doit implémenter les deux'],
  [/\b__enter__ est appelé quand\b/g, '__enter__ est appelé quand'],
  [/\b__exit__ can control exception handling\b/g, '__exit__ peut contrôler la gestion des exceptions'],
  [/\bby returning True to suppress\b/g, 'en retournant True pour supprimer'],
  [/\bWhen __exit__ retourne True\b/g, 'Quand __exit__ retourne True'],
  [/\bThe as keyword crée\b/g, 'Le mot-clé as crée'],
  [/\ballowing you to use\b/g, 'permettant d\'utiliser'],
  [/\ba different name in the current namespace\b/g, 'un nom différent dans l\'espace de noms courant'],
  [/\bThe as keyword can also create\b/g, 'Le mot-clé as peut aussi créer'],
  [/\bThe as keyword can also créer\b/g, 'Le mot-clé as peut aussi créer'],
  [/\bfor an entire module\b/g, 'pour un module entier'],
  [/\bQuand you write\b/g, 'Quand vous écrivez'],
  [/\bPython imports the module\b/g, 'Python importe le module'],
  [/\b__file__ is a special variable\b/g, '__file__ est une variable spéciale'],
  [/\bqui contient the path to\b/g, 'qui contient le chemin vers'],
  [/\bIt's automatically set by Python\b/g, 'Elle est automatiquement définie par Python'],
  [/\bwhen a module is loaded\b/g, 'quand un module est chargé'],
  [/\bThe __name__ variable contient\b/g, 'La variable __name__ contient'],
  [/\ble name of the module\b/g, 'le nom du module'],
  [/\bWhen a Python file is run directly\b/g, 'Quand un fichier Python est exécuté directement'],
  [/\b__name__ is set to\b/g, '__name__ est défini à'],
  [/\bdefaultdict from collections\b/g, 'defaultdict de collections'],
  [/\bautomatically creates default values\b/g, 'crée automatiquement des valeurs par défaut'],
  [/\bIf from collections import\b/g, 'Si from collections import'],
  [/\bnamedtuple from collections crée\b/g, 'namedtuple de collections crée'],
  [/\bcrée un tuple subclass\b/g, 'crée une sous-classe de tuple'],
  [/\bcrée a tuple subclass\b/g, 'crée une sous-classe de tuple'],
  [/\bwith named fields\b/g, 'avec des champs nommés'],
  [/\bA generator expression is\b/g, 'Une expression génératrice est'],
  [/\ba compact way to create\b/g, 'une façon concise de créer'],
  [/\bsimilar to a list comprehension\b/g, 'similaire à une compréhension de liste'],
  [/\bsimilar to une liste comprehension\b/g, 'similaire à une compréhension de liste'],
  [/\bbut with parentheses instead\b/g, 'mais avec des parenthèses au lieu'],
  [/\bOptional\[T\] from the typing module means\b/g, 'Optional[T] du module typing signifie'],
  [/\bthe type peut être T or None\b/g, 'le type peut être T ou None'],
  [/\bthe type can be T or None\b/g, 'le type peut être T ou None'],
  [/\bCalling popitem\(\) on an\b/g, 'Appeler popitem() sur un'],
  [/\bCalling popitem\(\) on a\b/g, 'Appeler popitem() sur un'],
  [/\bthere are no paires clé-valeur\b/g, 'il n\'y a pas de paires clé-valeur'],
  [/\bSi vous try to\b/g, 'Si vous essayez de'],
  [/\bLambda functions peut contenir\b/g, 'Les fonctions lambda peuvent contenir'],
  [/\bcrée an anonymous\b/g, 'crée une fonction anonyme'],
  [/\bC'est the fix for\b/g, 'C\'est la solution pour'],
  [/\bBy using a default parameter\b/g, 'En utilisant un paramètre par défaut'],
  [/\bthe current value of the loop\b/g, 'la valeur actuelle de la boucle'],
  [/\bwhen the object's reference count\b/g, 'quand le compteur de références de l\'objet'],
  [/\bdrops to zero\b/g, 'tombe à zéro'],
  [/\band the garbage coll\b/g, 'et le ramasse-miettes'],
  [/\b__del__ is Python's finalizer\b/g, '__del__ est le finaliseur de Python'],
  [/\bIt est appelé when\b/g, 'Il est appelé quand'],
  [/\bThe in operator checks\b/g, 'L\'opérateur in vérifie'],
  [/\bfor key membership\b/g, 'l\'appartenance des clés'],
  [/\bnot value membership\b/g, 'pas l\'appartenance des valeurs'],
  [/\bwith \.values\(\) checks\b/g, 'avec .values() vérifie'],
  [/\bwith \.items\(\) checks\b/g, 'avec .items() vérifie'],
  [/\bpaire clé-valeur membership\b/g, 'l\'appartenance des paires clé-valeur'],
  [/\bLambda functions with conditional\b/g, 'Les fonctions lambda avec des conditions'],
  [/\bevaluate the condition and\b/g, 'évaluent la condition et'],
  [/\brenvoyer the appropriate value\b/g, 'retournent la valeur appropriée'],
  [/\bAn iterable is any object\b/g, 'Un itérable est tout objet'],
  [/\bqui retourne an iterator\b/g, 'qui retourne un itérateur'],
  [/\bAn iterator is an object\b/g, 'Un itérateur est un objet'],
  [/\bThe built-in open\(\) function\b/g, 'La fonction intégrée open()'],
  [/\bretourne un file object\b/g, 'retourne un objet fichier'],
  [/\bthat implements the context\b/g, 'qui implémente le protocole de contexte'],
  [/\ba classe enfant est une sous-classe de all\b/g, 'une classe enfant est une sous-classe de tous'],
  [/\bIf class A: pass\b/g, 'Si class A: pass'],
  [/\bimports all public names\b/g, 'importe tous les noms publics'],
  [/\bnames not starting with underscore\b/g, 'les noms ne commençant pas par un underscore'],
  [/\bsys\.path is a list of\b/g, 'sys.path est une liste de'],
  [/\bsys\.path is une liste of\b/g, 'sys.path est une liste de'],
  [/\bdirectory paths where Python searches\b/g, 'chemins de répertoires où Python cherche'],
  [/\bwhen you import them\b/g, 'quand vous les importez'],
  [/\bQuand vous write import\b/g, 'Quand vous écrivez import'],
  [/\bis a built-in Python decorator\b/g, 'est un décorateur Python intégré'],
  [/\bqui crée a static method\b/g, 'qui crée une méthode statique'],
  [/\bne reçoit pas self or cls\b/g, 'ne reçoit pas self ni cls'],
  [/\bStatic methods ne reçoit pas\b/g, 'Les méthodes statiques ne reçoivent pas'],
  [/\bas the first argument\b/g, 'comme premier argument'],
  [/\bClass methods receive the class\b/g, 'Les méthodes de classe reçoivent la classe'],
  [/\bpermet treating individual objects\b/g, 'permet de traiter les objets individuels'],
  [/\ballows treating individual objects\b/g, 'permet de traiter les objets individuels'],
  [/\boperation\(\) calls le même\b/g, 'operation() appelle la même'],
  [/\bwhether they are individual\b/g, 'qu\'ils soient des objets individuels'],
  [/\bCurly braces \{\} avec\b/g, 'Les accolades {} avec'],
  [/\bcréer un dictionnaire in Python\b/g, 'créent un dictionnaire en Python'],
  [/\bis un dictionnaire\b/g, 'est un dictionnaire'],
  [/\bcontaining the\b/g, 'contenant les'],
  [/\bEmpty accolades \{\}\b/g, 'Les accolades vides {}'],
  [/\bcréer an dictionnaire vide\b/g, 'créent un dictionnaire vide'],
  [/\bis un dictionnaire literal\b/g, 'est un littéral de dictionnaire'],
  [/\bqui contient no key-value pairs\b/g, 'qui ne contient aucune paire clé-valeur'],
  [/\bDictionary access uses\b/g, 'L\'accès au dictionnaire utilise'],
  [/\bcrochets with la clé\b/g, 'des crochets avec la clé'],
  [/\bto retrieve the corresponding value\b/g, 'pour récupérer la valeur correspondante'],
  [/\bself in a method refers to\b/g, 'self dans une méthode fait référence à'],
  [/\bthe instance on which the method\b/g, 'l\'instance sur laquelle la méthode'],
  [/\b__iter__ must return self\b/g, '__iter__ doit retourner self'],
  [/\bC'est required so that\b/g, 'C\'est requis pour que'],
  [/\bpeut être utilisé directly in\b/g, 'puisse être utilisé directement dans'],
  [/\bWhen an iterator n'a pas more items\b/g, 'Quand un itérateur n\'a plus d\'éléments'],
  [/\bto yield, __next__ must raise\b/g, 'à produire, __next__ doit lever'],
  [/\bC'est the standard signal\b/g, 'C\'est le signal standard'],
  [/\bthat tells Python\b/g, 'qui indique à Python'],
  [/\bThe return value of __enter__\b/g, 'La valeur de retour de __enter__'],
  [/\bis bound to the variable\b/g, 'est liée à la variable'],
  [/\bspecified after 'as' in the 'with' statement\b/g, 'spécifiée après \'as\' dans l\'instruction \'with\''],
  [/\bC'est often 'self'\b/g, 'C\'est souvent \'self\''],
  [/\bThe with statement fournit un\b/g, 'L\'instruction with fournit une'],
  [/\bclean syntax for working with\b/g, 'syntaxe claire pour travailler avec'],
  [/\bcrée a context mana\b/g, 'crée un gestionnaire de contexte'],
  [/\bThe "w" mode opens\b/g, 'Le mode "w" ouvre'],
  [/\ba file for writing\b/g, 'un fichier en écriture'],
  [/\bIf the file already exists\b/g, 'Si le fichier existe déjà'],
  [/\bits contents are completely erased\b/g, 'son contenu est complètement effacé'],
  [/\bThe with statement \(context manager\)\b/g, 'L\'instruction with (gestionnaire de contexte)'],
  [/\bensures the file is automatically closed\b/g, 'assure que le fichier est fermé automatiquement'],
  [/\bwhen the block exits\b/g, 'quand le bloc se termine'],
  [/\bwhether it exits normally\b/g, 'qu\'il se termine normalement'],
  [/\bThe r prefix crée\b/g, 'Le préfixe r crée'],
  [/\bun raw string literal\b/g, 'un littéral de chaîne brute'],
  [/\bwhere backslashes are treated\b/g, 'où les backslashes sont traités'],
  [/\bas literal backslash characters\b/g, 'comme caractères backslash littéraux'],
  [/\bnot as escape seq\b/g, 'et non comme séquences d\'échappement'],
  [/\bThis test passes because\b/g, 'Ce test réussit car'],
  [/\band assertRaises\(ValueError\) is checking\b/g, 'et assertRaises(ValueError) vérifie'],
  [/\bthat a ValueError is rai\b/g, 'qu\'une ValueError est levée'],
  [/\bAssert statements can be completely disabled\b/g, 'Les instructions assert peuvent être complètement désactivées'],
  [/\bby running Python with the -O\b/g, 'en exécutant Python avec l\'option -O'],
  [/\bWhen Python runs in optimize\b/g, 'Quand Python s\'exécute en mode optimisation'],
  [/\b'async with' is the asynchronous version\b/g, '\'async with\' est la version asynchrone'],
  [/\bof the 'with' statement\b/g, 'de l\'instruction \'with\''],
  [/\bIt fonctionne avec asynchronous\b/g, 'Il fonctionne avec des'],
  [/\basynchronous context managers\b/g, 'gestionnaires de contexte asynchrones'],
  [/\bThe 'with' statement is the Pythonic way\b/g, 'L\'instruction \'with\' est la façon pythonique'],
  [/\bto handle resources like files\b/g, 'de gérer les ressources comme les fichiers'],
  [/\bIt guarantees proper cleanup\b/g, 'Elle garantit un nettoyage correct'],
];

let count = 0;
for (const [pattern, repl] of replacements) {
  const before = content;
  content = content.replace(pattern, repl);
  if (before !== content) {
    const n = (before.match(pattern) || []).length;
    count += n;
  }
}

fs.writeFileSync(filePath, content);
console.log('Applied replacements. Estimated changes:', count);