#!/usr/bin/env python3
"""
Generate French translations for IDs 2501-2650 from extracted_2501_2650.json
Output: scripts/fr_2501_2650_translations.ts
"""
import json
import re

# Section header mappings
HEADERS = {
    "Key concepts:": "Concepts clés :",
    "How it works:": "Comment ça fonctionne :",
    "Example:": "Exemple :",
    "Common uses:": "Usages courants :",
    "Fix:": "Corrigé :",
    "Note:": "Note :",
    "The type/object relationship:": "La relation type/object :",
    "Why this matters:": "Pourquoi c'est important :",
    "Comparison:": "Comparaison :",
    "Why immutable:": "Pourquoi immuable :",
    "Timeline:": "Chronologie :",
    "Note on aliases:": "Note sur les alias :",
    "isinstance vs type:": "isinstance vs type :",
    "__bases__ vs __mro__:": "__bases__ vs __mro__ :",
    "type(self) vs self.__class__:": "type(self) vs self.__class__ :",
    "Symmetry check:": "Vérification de symétrie :",
    "When to use each:": "Quand utiliser chacun :",
    "Anti-pattern (breaks subclassing):": "Anti-pattern (casse l'héritage) :",
    "Best practice:": "Bonne pratique :",
    "Comparison table:": "Tableau comparatif :",
    "How it works step by step:": "Comment ça fonctionne étape par étape :",
    "The modulo approach works for all integers:": "L'approche modulo fonctionne pour tous les entiers :",
    "When to use composition:": "Quand utiliser la composition :",
    "When to use inheritance:": "Quand utiliser l'héritage :",
}

# Common phrase translations (order matters - longer first)
PHRASES = [
    # MRO & inheritance
    ("Every Python class implicitly inherits from object", "Toute classe Python hérite implicitement de object"),
    ("The __mro__ attribute shows the tuple of classes Python searches through when resolving attributes or methods", "L'attribut __mro__ affiche le tuple des classes que Python parcourt pour résoudre les attributs ou méthodes"),
    ("returns the method resolution order as a tuple", "retourne l'ordre de résolution des méthodes sous forme de tuple"),
    ("Every class ultimately inherits from object", "Toute classe hérite ultimement de object"),
    ("A single class with no explicit parent has MRO", "Une classe sans parent explicite a un MRO"),
    ("Python uses C3 linearization to compute the MRO", "Python utilise la linéarisation C3 pour calculer le MRO"),
    ("creates a class that implicitly inherits from object", "crée une classe qui hérite implicitement de object"),
    ("Python first looks in A, then in object", "Python cherche d'abord dans A, puis dans object"),
    ("Single inheritance creates a linear MRO chain", "L'héritage simple crée une chaîne MRO linéaire"),
    ("The class itself always comes first in its own MRO", "La classe elle-même est toujours en tête dans son propre MRO"),
    ("Parent classes follow in inheritance order", "Les classes parentes suivent dans l'ordre d'héritage"),
    ("object is always last", "object est toujours en dernier"),
    ("means B inherits from A", "signifie que B hérite de A"),
    ("Attribute lookup searches B first, then A, then object", "La recherche d'attribut cherche d'abord dans B, puis A, puis object"),
    ("When B explicitly inherits from A", "Quand B hérite explicitement de A"),
    ("the MRO chains them together", "le MRO les enchaîne"),
    ("B first, then A, then the ultimate base object", "B d'abord, puis A, puis l'objet de base ultime"),
    ("A chain of single inheritance produces a simple linear MRO", "Une chaîne d'héritage simple produit un MRO linéaire simple"),
    ("Each class appears once in the order from most derived to most base", "Chaque classe apparaît une fois dans l'ordre du plus dérivé au plus de base"),
    ("MRO follows the chain from child to ultimate parent", "Le MRO suit la chaîne de l'enfant au parent ultime"),
    ("Each class appears exactly once in the MRO", "Chaque classe apparaît exactement une fois dans le MRO"),
    ("object is always the final entry", "object est toujours l'entrée finale"),
    ("C inherits from B, B inherits from A, A inherits from object", "C hérite de B, B hérite de A, A hérite de object"),
    ("Method lookup proceeds in this exact order", "La recherche de méthode suit cet ordre exact"),
    ("When a class inherits from multiple unrelated parents", "Quand une classe hérite de plusieurs parents non liés"),
    ("the MRO places them in the order they appear in the class definition", "le MRO les place dans l'ordre où ils apparaissent dans la définition de classe"),
    ("followed by object", "suivi de object"),
    ("means A is checked before B", "signifie que A est vérifié avant B"),
    ("The order of base classes in the class definition matters", "L'ordre des classes de base dans la définition de classe compte"),
    ("Unrelated parents are linearized left-to-right", "Les parents non liés sont linéarisés de gauche à droite"),
    ("object appears once at the end", "object apparaît une fois à la fin"),
    ("A is the first parent, B is the second", "A est le premier parent, B le second"),
    ("Attribute lookup: C → A → B → object", "Recherche d'attribut : C → A → B → object"),
    ("The order of base classes directly determines the MRO", "L'ordre des classes de base détermine directement le MRO"),
    ("Changing C(A, B) to C(B, A) reverses which parent is searched first", "Changer C(A, B) en C(B, A) inverse quel parent est cherché en premier"),
    ("means B is checked before A", "signifie que B est vérifié avant A"),
    ("This is the opposite order from C(A, B)", "C'est l'ordre inverse de C(A, B)"),
    ("The programmer controls method resolution priority by choosing base order", "Le programmeur contrôle la priorité de résolution des méthodes en choisissant l'ordre des bases"),
    ("This is a fundamental design decision in multiple inheritance", "C'est une décision de conception fondamentale en héritage multiple"),
    ("B is listed first, A second", "B est listé en premier, A en second"),
    ("If both A and B define a method, B's version is found first", "Si A et B définissent une méthode, la version de B est trouvée en premier"),
    ("Python adopted the C3 linearization algorithm", "Python a adopté l'algorithme de linéarisation C3"),
    ("and it's the only algorithm used in Python 3", "et c'est le seul algorithme utilisé en Python 3"),
    ("C3 linearization guarantees a consistent and predictable MRO", "La linéarisation C3 garantit un MRO cohérent et prévisible"),
    ("It preserves local precedence order", "Elle préserve l'ordre de priorité local"),
    ("order of bases in class definition", "ordre des bases dans la définition de classe"),
    ("It preserves monotonicity", "Elle préserve la monotonie"),
    ("if A comes before B in a parent's MRO, A also comes before B in child's MRO", "si A précède B dans le MRO d'un parent, A précède aussi B dans le MRO de l'enfant"),
    ("It raises TypeError if no valid linearization exists", "Elle lève TypeError si aucune linéarisation valide n'existe"),
    ("C3 merges the linearizations of parent classes with the list of parents", "C3 fusionne les linéarisations des classes parentes avec la liste des parents"),
    ("It picks the first head that doesn't appear in the tail of any other list", "Il choisit le premier élément de tête qui n'apparaît pas dans la queue d'aucune autre liste"),
    ("This process repeats until all classes are linearized", "Ce processus se répète jusqu'à ce que toutes les classes soient linéarisées"),
    ("If no valid head is found, TypeError is raised", "Si aucun élément de tête valide n'est trouvé, TypeError est levée"),
    ("The diamond inheritance pattern is when two classes (B and C) inherit from the same parent (A)", "Le motif d'héritage en diamant survient quand deux classes (B et C) héritent du même parent (A)"),
    ("and a fourth class (D) inherits from both B and C", "et une quatrième classe (D) hérite à la fois de B et C"),
    ("C3 linearization ensures A appears only once", "La linéarisation C3 assure que A n'apparaît qu'une fois"),
    ("after all its children", "après tous ses enfants"),
    ("Diamond: A is the common ancestor of B and C", "Diamant : A est l'ancêtre commun de B et C"),
    ("D inherits from both B and C", "D hérite à la fois de B et C"),
    ("A must come after both B and C in the MRO", "A doit apparaître après B et C dans le MRO"),
    ("since both depend on A", "puisque tous deux dépendent de A"),
    ("C3 ensures each class appears exactly once", "C3 assure que chaque classe apparaît exactement une fois"),
    ("The order of D's bases (B, C) determines B comes before C", "L'ordre des bases de D (B, C) détermine que B précède C"),
    ("merge B's MRO (B, A, object) with C's MRO (C, A, object) and bases [B, C]", "fusionner le MRO de B (B, A, object) avec celui de C (C, A, object) et les bases [B, C]"),
    ("Pick D first, then B", "Choisir D d'abord, puis B"),
    ("head of B's MRO, not in tail of others", "tête du MRO de B, pas dans la queue des autres"),
    ("Then C (head of C's MRO), then A, then object", "Puis C (tête du MRO de C), puis A, puis object"),
    ("Result:", "Résultat :"),
    ("When D inherits from B and C (both inheriting from A)", "Quand D hérite de B et C (tous deux héritant de A)"),
    ("the MRO is (D, B, C, A, object)", "le MRO est (D, B, C, A, object)"),
    ("Method lookup follows this order", "La recherche de méthode suit cet ordre"),
    ("D doesn't define f — check next in MRO", "D ne définit pas f — vérifier le suivant dans le MRO"),
    ("B doesn't define f either — check next", "B ne définit pas f non plus — vérifier le suivant"),
    ("C defines f returning \"C\" — found!", "C définit f retournant \"C\" — trouvé !"),
    ("A's f returning \"A\" is never reached because C's f is found first", "Le f de A retournant \"A\" n'est jamais atteint car le f de C est trouvé en premier"),
    ("D().f() triggers method lookup along D's MRO", "D().f() déclenche la recherche de méthode le long du MRO de D"),
    ("D has no f, B has no f, C has f → return \"C\"", "D n'a pas f, B n'a pas f, C a f → retourne \"C\""),
    ("This demonstrates why MRO matters", "Cela démontre pourquoi le MRO compte"),
    ("even though B is listed first in D's bases", "même si B est listé en premier dans les bases de D"),
    ("C's method wins because B doesn't override it", "La méthode de C l'emporte car B ne la surcharge pas"),
    ("C is checked before A in the MRO", "C est vérifié avant A dans le MRO"),
    ("C3 linearization can fail when the inheritance hierarchy has contradictory ordering constraints", "La linéarisation C3 peut échouer quand la hiérarchie d'héritage a des contraintes d'ordre contradictoires"),
    ("Python raises a TypeError at class creation time", "Python lève une TypeError au moment de la création de la classe"),
    ("C3 linearization has strict rules about ordering consistency", "La linéarisation C3 a des règles strictes sur la cohérence de l'ordre"),
    ("If parent order contradicts a base class's MRO, it fails", "Si l'ordre des parents contredit le MRO d'une classe de base, ça échoue"),
    ("The error is raised when the class is defined, not when it's used", "L'erreur est levée quand la classe est définie, pas quand elle est utilisée"),
    ("The error message says", "Le message d'erreur indique"),
    ("Cannot create a consistent method resolution order", "Cannot create a consistent method resolution order"),
    ("C3 tries to merge parent MROs respecting local precedence", "C3 tente de fusionner les MRO parents en respectant la priorité locale"),
    ("If a class appears as a \"head\" in one list but in the \"tail\" of another", "Si une classe apparaît comme \"tête\" dans une liste mais dans la \"queue\" d'une autre"),
    ("and no valid pick exists, it fails", "et aucun choix valide n'existe, ça échoue"),
    ("This prevents ambiguous method resolution", "Cela évite une résolution de méthode ambiguë"),
    ("A appears before B in C's bases, but B's MRO has A after B — contradiction", "A apparaît avant B dans les bases de C, mais le MRO de B a A après B — contradiction"),
    ("This is the classic example of an inconsistent MRO", "C'est l'exemple classique d'un MRO incohérent"),
    ("The conflict arises because C's base list says \"A before B\" but B's own MRO says \"B before A\"", "Le conflit survient car la liste des bases de C dit \"A avant B\" mais le MRO propre de B dit \"B avant A\""),
    ("C(A, B) says: search A before B", "C(A, B) dit : chercher A avant B"),
    ("But B inherits from A", "Mais B hérite de A"),
    ("so B's MRO is (B, A, object) — B before A", "donc le MRO de B est (B, A, object) — B avant A"),
    ("These two constraints contradict each other", "Ces deux contraintes se contredisent"),
    ("C3 linearization cannot satisfy both, so TypeError is raised", "La linéarisation C3 ne peut satisfaire les deux, donc TypeError est levée"),
    ("To build C's MRO, C3 must merge:", "Pour construire le MRO de C, C3 doit fusionner :"),
    ("A's MRO (A, object), B's MRO (B, A, object), and bases [A, B]", "le MRO de A (A, object), le MRO de B (B, A, object), et les bases [A, B]"),
    ("A is a head in A's MRO", "A est une tête dans le MRO de A"),
    ("but A also appears in the tail of B's MRO (B, A, object)", "mais A apparaît aussi dans la queue du MRO de B (B, A, object)"),
    ("B is a head in B's MRO", "B est une tête dans le MRO de B"),
    ("but A must come first per C's base list", "mais A doit venir en premier selon la liste des bases de C"),
    ("No valid ordering exists", "Aucun ordre valide n'existe"),
    ("The inconsistency is a direct conflict between two ordering constraints", "L'incohérence est un conflit direct entre deux contraintes d'ordre"),
    ("that C3 linearization must respect simultaneously", "que la linéarisation C3 doit respecter simultanément"),
    ("Constraint 1 (from C's base list): A must come before B", "Contrainte 1 (liste des bases de C) : A doit venir avant B"),
    ("Constraint 2 (from B's MRO): B must come before A (since B inherits from A)", "Contrainte 2 (MRO de B) : B doit venir avant A (puisque B hérite de A)"),
    ("These two constraints are mutually exclusive", "Ces deux contraintes sont mutuellement exclusives"),
    ("C3 linearization enforces both, so it fails", "La linéarisation C3 applique les deux, donc ça échoue"),
    ("bases list says: A, then B", "la liste des bases dit : A, puis B"),
    ("B's MRO says: B, then A", "le MRO de B dit : B, puis A"),
    ("For C's MRO, A must precede B (base list order) AND B must precede A (B's linearization)", "Pour le MRO de C, A doit précéder B (ordre de la liste des bases) ET B doit précéder A (linéarisation de B)"),
    ("Both can't be true", "Les deux ne peuvent être vrais"),
    ("This works! B before A is consistent with B's MRO", "Cela fonctionne ! B avant A est cohérent avec le MRO de B"),
    ("When both B and C override f", "Quand B et C surchargent tous deux f"),
    ("the MRO determines which one D uses", "le MRO détermine lequel D utilise"),
    ("Since B comes before C in D's MRO", "Puisque B précède C dans le MRO de D"),
    ("B's version wins", "La version de B l'emporte"),
    ("D's MRO is (D, B, C, A, object)", "Le MRO de D est (D, B, C, A, object)"),
    ("D doesn't define f — look in B", "D ne définit pas f — chercher dans B"),
    ("B defines f returning \"B\" — found!", "B définit f retournant \"B\" — trouvé !"),
    ("C's f and A's f are never reached", "Le f de C et celui de A ne sont jamais atteints"),
    ("B is listed first in bases", "B est listé en premier dans les bases"),
    ("D().f() → D has no f → check B → B has f → return \"B\"", "D().f() → D n'a pas f → vérifier B → B a f → retourner \"B\""),
    ("C's f(\"C\") is shadowed because B appears earlier in the MRO", "Le f(\"C\") de C est masqué car B apparaît plus tôt dans le MRO"),
    ("Compare with Q8 where B did NOT define f — then C's f was used", "Comparer avec Q8 où B ne définissait PAS f — la méthode de C était alors utilisée"),
    # super(), proxy, delegation
    ("A common misconception is that super() simply calls the parent class.", "Une idée reçue fréquente : super() appellerait simplement la classe parente."),
    ("In reality, super() delegates to the next class in the MRO chain.", "En réalité, super() délègue à la classe suivante dans la chaîne MRO."),
    ("super() returns a proxy that delegates to the next class in MRO", "super() retourne un proxy qui délègue à la classe suivante dans le MRO"),
    ("\"Next class\" depends on where in the MRO the current class is", "\"Classe suivante\" dépend de la position dans le MRO de la classe actuelle"),
    ("This enables cooperative multiple inheritance", "Cela permet l'héritage multiple coopératif"),
    ("The MRO is determined by the actual instance's class, not the class where super() is written", "Le MRO est déterminé par la classe réelle de l'instance, pas la classe où super() est écrit"),
    ("In class B, super() points to the next class after B in the MRO of the actual object", "Dans la classe B, super() pointe vers la classe suivante après B dans le MRO de l'objet actuel"),
    ("If the object is of class D(B, C) with MRO (D, B, C, A, object), then super() in B goes to C, not A", "Si l'objet est de classe D(B, C) avec MRO (D, B, C, A, object), alors super() dans B va vers C, pas A"),
    ("This is why super() is called \"cooperative\" — each class cooperates by calling super()", "C'est pourquoi super() est dit \"coopératif\" — chaque classe coopère en appelant super()"),
    ("This is the classic demonstration of cooperative super() in a diamond hierarchy.", "C'est la démonstration classique de super() coopératif dans une hiérarchie en diamant."),
    ("Each super() call follows the MRO, not the direct parent.", "Chaque appel super() suit le MRO, pas le parent direct."),
    ("super() in B goes to C (next in D's MRO after B), NOT to A", "super() dans B va vers C (suivant dans le MRO de D après B), PAS vers A"),
    ("super() in C goes to A (next in D's MRO after C)", "super() dans C va vers A (suivant dans le MRO de D après C)"),
    ("The call chain builds the string from the bottom up", "La chaîne d'appels construit la chaîne du bas vers le haut"),
    ("D().f() → D has no f → call B.f() (next in MRO)", "D().f() → D n'a pas f → appeler B.f() (suivant dans le MRO)"),
    ("B.f(): super().f() + \"B\" → super() in B is C (in D's MRO)", "B.f(): super().f() + \"B\" → super() dans B est C (dans le MRO de D)"),
    ("C.f(): super().f() + \"C\" → super() in C is A (in D's MRO)", "C.f(): super().f() + \"C\" → super() dans C est A (dans le MRO de D)"),
    ("A.f(): return \"A\"", "A.f(): return \"A\""),
    ("Back to C.f(): \"A\" + \"C\" = \"AC\"", "Retour à C.f(): \"A\" + \"C\" = \"AC\""),
    ("Back to B.f(): \"AC\" + \"B\" = \"ACB\"", "Retour à B.f(): \"AC\" + \"B\" = \"ACB\""),
    ("The key insight: super() in B goes to C, not A!", "L'idée clé : super() dans B va vers C, pas A !"),
    ("Using super().__init__() in a subclass ensures the parent's initialization runs", "Utiliser super().__init__() dans une sous-classe assure que l'initialisation du parent s'exécute"),
    ("setting up inherited attributes", "configurant les attributs hérités"),
    ("B.__init__ calls super().__init__() which runs A.__init__", "B.__init__ appelle super().__init__() qui exécute A.__init__"),
    ("A.__init__ sets self.a = \"A\" on the instance", "A.__init__ définit self.a = \"A\" sur l'instance"),
    ("Then B.__init__ continues and sets self.b = \"B\"", "Puis B.__init__ continue et définit self.b = \"B\""),
    ("The instance has both attributes: a=\"A\" and b=\"B\"", "L'instance a les deux attributs : a=\"A\" et b=\"B\""),
    ("B() creates a new instance, calls B.__init__", "B() crée une nouvelle instance, appelle B.__init__"),
    ("super().__init__() inside B calls A.__init__(self)", "super().__init__() dans B appelle A.__init__(self)"),
    ("A.__init__ sets self.a = \"A\"", "A.__init__ définit self.a = \"A\""),
    ("Back in B.__init__, self.b = \"B\" is set", "De retour dans B.__init__, self.b = \"B\" est défini"),
    ("B().a accesses the attribute set by A → \"A\"", "B().a accède à l'attribut défini par A → \"A\""),
    ("Without super(), diamond inheritance can cause the shared ancestor's __init__ to run multiple times.", "Sans super(), l'héritage en diamant peut faire exécuter __init__ de l'ancêtre partagé plusieurs fois."),
    ("Cooperative super() solves this by following the MRO.", "Le super() coopératif résout cela en suivant le MRO."),
    ("In a diamond A ← B, A ← C, B,C ← D, A's __init__ should run once", "Dans un diamant A ← B, A ← C, B,C ← D, __init__ de A doit s'exécuter une fois"),
    ("If B and C both call A.__init__(self) directly, A's __init__ runs twice", "Si B et C appellent tous deux A.__init__(self) directement, __init__ de A s'exécute deux fois"),
    ("If B and C both call super().__init__(), MRO ensures A.__init__ runs once", "Si B et C appellent tous deux super().__init__(), le MRO assure que __init__ de A s'exécute une fois"),
    ("This is the \"cooperative\" pattern", "C'est le motif \"coopératif\""),
    ("D.__init__ calls super().__init__() → goes to B", "D.__init__ appelle super().__init__() → va vers B"),
    ("B.__init__ calls super().__init__() → goes to C (not A!)", "B.__init__ appelle super().__init__() → va vers C (pas A !)"),
    ("C.__init__ calls super().__init__() → goes to A", "C.__init__ appelle super().__init__() → va vers A"),
    ("A.__init__ calls super().__init__() → goes to object", "A.__init__ appelle super().__init__() → va vers object"),
    ("Each class's __init__ runs exactly once", "Le __init__ de chaque classe s'exécute exactement une fois"),
    ("prints D, B, C, A — each exactly once", "affiche D, B, C, A — chacun exactement une fois"),
    ("Attribute lookup follows the MRO.", "La recherche d'attribut suit le MRO."),
    ("The first class in the MRO that defines the attribute wins.", "La première classe dans le MRO qui définit l'attribut l'emporte."),
    ("D doesn't define x — check B", "D ne définit pas x — vérifier B"),
    ("B defines x = 2 — found! Return 2", "B définit x = 2 — trouvé ! Retourner 2"),
    ("C (no x) and A (x=1) are never reached", "C (pas de x) et A (x=1) ne sont jamais atteints"),
    ("D.x triggers attribute lookup along the MRO", "D.x déclenche la recherche d'attribut le long du MRO"),
    ("D has no x → B has x = 2 → return 2", "D n'a pas x → B a x = 2 → retourner 2"),
    ("Even though A also has x = 1, B is checked first", "Même si A a aussi x = 1, B est vérifié en premier"),
    ("— from B", "— de B"),
    ("C has no x, falls through to A", "C n'a pas x, passe à A"),
    ("When B doesn't define x", "Quand B ne définit pas x"),
    ("the MRO continues to C, which does define x=3", "le MRO continue vers C, qui définit bien x=3"),
    ("A's x=1 is further down the chain and never reached", "Le x=1 de A est plus bas dans la chaîne et n'est jamais atteint"),
    ("D has no x, B has no x, C has x = 3 — found!", "D n'a pas x, B n'a pas x, C a x = 3 — trouvé !"),
    ("A's x = 1 is shadowed by C's x = 3", "Le x = 1 de A est masqué par le x = 3 de C"),
    ("This demonstrates that MRO isn't just \"depth first\" — siblings matter", "Cela démontre que le MRO n'est pas juste \"profondeur d'abord\" — les frères comptent"),
    ("D.x → D (no x) → B (no x) → C (x=3) → return 3", "D.x → D (pas de x) → B (pas de x) → C (x=3) → retourner 3"),
    ("If C also had no x, then A (x=1) would be found", "Si C n'avait pas non plus x, alors A (x=1) serait trouvé"),
    ("The MRO ensures C is checked before A in the diamond", "Le MRO assure que C est vérifié avant A dans le diamant"),
    ("— from C", "— de C"),
    ("B has no x, falls through to A (not C, since C isn't in B's MRO)", "B n'a pas x, passe à A (pas C, car C n'est pas dans le MRO de B)"),
    ("C defines it directly", "C le définit directement"),
    ("Built-in types also have MROs.", "Les types intégrés ont aussi des MRO."),
    ("list is a direct subclass of object with no intermediate classes.", "list est une sous-classe directe de object sans classes intermédiaires."),
    ("list inherits directly from object", "list hérite directement de object"),
    ("Similarly, tuple.__mro__", "De même, tuple.__mro__"),
    ("Built-in types follow the same MRO rules as user-defined classes", "Les types intégrés suivent les mêmes règles MRO que les classes définies par l'utilisateur"),
    ("list has no explicit Python-level parent other than object", "list n'a pas de parent explicite au niveau Python autre que object"),
    ("The MRO is simply (list, object)", "Le MRO est simplement (list, object)"),
    ("This is the same structure as any simple user-defined class", "C'est la même structure que toute classe simple définie par l'utilisateur"),
    ("One of Python's lesser-known facts: bool is a subclass of int.", "Un fait peu connu de Python : bool est une sous-classe de int."),
    ("True is 1 and False is 0 in integer context.", "True vaut 1 et False vaut 0 dans un contexte entier."),
    ("bool inherits from int — this is by design", "bool hérite de int — c'est voulu"),
    ("True + True = 2, True * 5 = 5 — because bool IS int", "True + True = 2, True * 5 = 5 — car bool EST int"),
    ("issubclass(bool, int) returns True", "issubclass(bool, int) retourne True"),
    ("bool was added to Python as a subclass of int for backward compatibility", "bool a été ajouté à Python comme sous-classe de int pour la rétrocompatibilité"),
    ("True and False are instances of bool, which is a subclass of int", "True et False sont des instances de bool, qui est une sous-classe de int"),
    ("All int operations work on booleans", "Toutes les opérations int fonctionnent sur les booléens"),
    ("super() doesn't return the parent class or an instance of it.", "super() ne retourne pas la classe parente ni une instance de celle-ci."),
    ("It returns a special proxy object that knows how to forward attribute lookups to the appropriate class in the MRO.", "Il retourne un objet proxy spécial qui sait comment transférer les recherches d'attributs vers la classe appropriée dans le MRO."),
    ("super() returns a proxy (not a class, not an instance)", "super() retourne un proxy (pas une classe, pas une instance)"),
    ("The proxy delegates attribute access to the next class in the MRO", "Le proxy délègue l'accès aux attributs à la classe suivante dans le MRO"),
    ("\"Next class\" is relative to the class where super() is called", "\"Classe suivante\" est relative à la classe où super() est appelé"),
    ("The proxy uses the MRO of the actual instance's type", "Le proxy utilise le MRO du type réel de l'instance"),
    ("super() inside class B creates a proxy bound to B and self", "super() dans la classe B crée un proxy lié à B et self"),
    ("When you call super().method(), the proxy finds method in the next class after B in self's MRO", "Quand vous appelez super().method(), le proxy trouve method dans la classe suivante après B dans le MRO de self"),
    ("This enables cooperative method calls across the inheritance chain", "Cela permet les appels de méthodes coopératifs à travers la chaîne d'héritage"),
    ("super().f() in B delegates to A's f method, which returns 1.", "super().f() dans B délègue à la méthode f de A, qui retourne 1."),
    ("B's f then adds 1 to get 2.", "Le f de B ajoute ensuite 1 pour obtenir 2."),
    ("B().f() calls B's f method", "B().f() appelle la méthode f de B"),
    ("super().f() inside B calls A's f method", "super().f() dans B appelle la méthode f de A"),
    ("A.f() returns 1", "A.f() retourne 1"),
    ("B.f() returns 1 + 1 = 2", "B.f() retourne 1 + 1 = 2"),
    ("B().f() → calls B.f(self)", "B().f() → appelle B.f(self)"),
    ("super().f() → proxy delegates to A.f(self) → returns 1", "super().f() → le proxy délègue à A.f(self) → retourne 1"),
    ("1 + 1 = 2", "1 + 1 = 2"),
    ("B.f returns 2", "B.f retourne 2"),
    ("Each super() call in the chain adds 1 to the result from the next class in the MRO.", "Chaque appel super() dans la chaîne ajoute 1 au résultat de la classe suivante dans le MRO."),
    ("C's MRO is (C, B, A, object)", "Le MRO de C est (C, B, A, object)"),
    ("C.f() calls super().f() → B.f()", "C.f() appelle super().f() → B.f()"),
    ("B.f() calls super().f() → A.f()", "B.f() appelle super().f() → A.f()"),
    ("Each level adds 1", "Chaque niveau ajoute 1"),
    ("super().f() in C → B.f(self) → super().f() in B → A.f(self) → 1", "super().f() dans C → B.f(self) → super().f() dans B → A.f(self) → 1"),
    ("B.f returns 1 + 1 = 2", "B.f retourne 1 + 1 = 2"),
    ("C.f returns 2 + 1 = 3", "C.f retourne 2 + 1 = 3"),
    ("Each level adds 1 through the super() chain", "Chaque niveau ajoute 1 à travers la chaîne super()"),
    ("super() is not restricted to __init__.", "super() n'est pas limité à __init__."),
    ("It can be used in any instance method, class method, or property to delegate to the next class in the MRO.", "Il peut être utilisé dans toute méthode d'instance, méthode de classe ou propriété pour déléguer à la classe suivante dans le MRO."),
    ("super() works in __init__, regular methods, class methods, and properties", "super() fonctionne dans __init__, les méthodes régulières, les méthodes de classe et les propriétés"),
    ("It always follows the MRO regardless of which method it's used in", "Il suit toujours le MRO quelle que soit la méthode où il est utilisé"),
    ("Common uses include extending parent behavior in any method", "Les usages courants incluent l'extension du comportement du parent dans toute méthode"),
    ("The only restriction is that it doesn't work in static methods (no instance/class context)", "La seule restriction est qu'il ne fonctionne pas dans les méthodes statiques (pas de contexte instance/classe)"),
    ("super() needs either an implicit or explicit class and instance/class reference", "super() a besoin d'une référence implicite ou explicite à la classe et à l'instance/classe"),
    ("In instance methods: super() uses the class where it's defined and self", "Dans les méthodes d'instance : super() utilise la classe où il est défini et self"),
    ("In class methods: super() uses the class where it's defined and cls", "Dans les méthodes de classe : super() utilise la classe où il est défini et cls"),
    ("In static methods: no self or cls available, so super() doesn't work", "Dans les méthodes statiques : pas de self ni cls disponibles, donc super() ne fonctionne pas"),
    ("super() works with @classmethod.", "super() fonctionne avec @classmethod."),
    ("In Python 3, super() inside a classmethod automatically uses the correct class context.", "En Python 3, super() dans une méthode de classe utilise automatiquement le bon contexte de classe."),
    ("@classmethod receives cls instead of self", "@classmethod reçoit cls au lieu de self"),
    ("super() inside a classmethod still works correctly", "super() dans une méthode de classe fonctionne toujours correctement"),
    ("super().f() delegates to A's classmethod f", "super().f() délègue à la méthode de classe f de A"),
    ("The result is \"A\" + \"B\" = \"AB\"", "Le résultat est \"A\" + \"B\" = \"AB\""),
    ("B.f() → calls B's classmethod f with cls=B", "B.f() → appelle la méthode de classe f de B avec cls=B"),
    ("super().f() → proxy delegates to A.f(cls=B) → returns \"A\"", "super().f() → le proxy délègue à A.f(cls=B) → retourne \"A\""),
    ("\"A\" + \"B\" = \"AB\"", "\"A\" + \"B\" = \"AB\""),
    ("B.f() returns \"AB\"", "B.f() retourne \"AB\""),
    ("super() in classmethods follows the same MRO rules", "super() dans les classmethods suit les mêmes règles MRO"),
    ("super(A, A()) creates a proxy that looks up methods starting from the class after A in A's MRO.", "super(A, A()) crée un proxy qui cherche les méthodes à partir de la classe après A dans le MRO de A."),
    ("A's MRO is (A, object)", "Le MRO de A est (A, object)"),
    ("super(A, instance) means: start looking after A in the MRO", "super(A, instance) signifie : commencer à chercher après A dans le MRO"),
    ("The next (and only remaining) class after A is object", "La classe suivante (et seule restante) après A est object"),
    ("So super(A, A()) proxies for object", "Donc super(A, A()) fait proxy pour object"),
    ("super(A, A()) — first arg is \"start after A\", second arg is the instance", "super(A, A()) — premier arg \"commencer après A\", deuxième arg l'instance"),
    ("After A in the MRO comes object", "Après A dans le MRO vient object"),
    ("Any method call on this proxy will look in object", "Tout appel de méthode sur ce proxy cherchera dans object"),
    ("— from object", "— de object"),
    ("super().__init__() allows the subclass to pass specific arguments to the parent's __init__", "super().__init__() permet à la sous-classe de passer des arguments spécifiques au __init__ du parent"),
    ("while adding its own initialization.", "tout en ajoutant sa propre initialisation."),
    ("B.__init__ takes both x and y", "B.__init__ prend à la fois x et y"),
    ("super().__init__(x) forwards only x to A.__init__", "super().__init__(x) transmet uniquement x à A.__init__"),
    ("A sets self.x = x (which is 1)", "A définit self.x = x (qui vaut 1)"),
    ("B then sets self.y = y (which is 2)", "B définit ensuite self.y = y (qui vaut 2)"),
    ("The instance has both attributes", "L'instance a les deux attributs"),
    ("B(1, 2) calls B.__init__(self, 1, 2)", "B(1, 2) appelle B.__init__(self, 1, 2)"),
    ("super().__init__(1) calls A.__init__(self, 1)", "super().__init__(1) appelle A.__init__(self, 1)"),
    ("A sets self.x = 1", "A définit self.x = 1"),
    ("Back in B, self.y = 2", "De retour dans B, self.y = 2"),
    ("b.x = 1, b.y = 2", "b.x = 1, b.y = 2"),
    ("set by A.__init__", "défini par A.__init__"),
    ("set by B.__init__", "défini par B.__init__"),
    ("The order of print statements depends on where super().__init__() is called relative to the print in B.__init__.", "L'ordre des print dépend de l'emplacement de super().__init__() par rapport au print dans B.__init__."),
    ("B.__init__ runs: print(\"B\") first, then super().__init__()", "B.__init__ s'exécute : print(\"B\") d'abord, puis super().__init__()"),
    ("super().__init__() calls A.__init__ which prints \"A\"", "super().__init__() appelle A.__init__ qui affiche \"A\""),
    ("Result: \"B\" is printed first, then \"A\"", "Résultat : \"B\" est affiché d'abord, puis \"A\""),
    ("If super().__init__() were called before print(\"B\"), the order would reverse", "Si super().__init__() était appelé avant print(\"B\"), l'ordre serait inversé"),
    ("B() → B.__init__(self)", "B() → B.__init__(self)"),
    ("print(\"B\") → outputs \"B\"", "print(\"B\") → affiche \"B\""),
    ("print(\"A\") → outputs \"A\"", "print(\"A\") → affiche \"A\""),
    ("Output: B, then A", "Sortie : B, puis A"),
    ("This shows super() used in a regular method (not __init__) to extend the parent's behavior.", "Cela montre super() utilisé dans une méthode régulière (pas __init__) pour étendre le comportement du parent."),
    ("B.greet() calls super().greet() to get A's result", "B.greet() appelle super().greet() pour obtenir le résultat de A"),
    ("A.greet() returns \"Hello\"", "A.greet() retourne \"Hello\""),
    ("B.greet() concatenates \" World\" to get \"Hello World\"", "B.greet() concatène \" World\" pour obtenir \"Hello World\""),
    ("This is the \"extend parent behavior\" pattern", "C'est le motif \"étendre le comportement du parent\""),
    ("B().greet() → B.greet(self)", "B().greet() → B.greet(self)"),
    ("super().greet() → A.greet(self) → \"Hello\"", "super().greet() → A.greet(self) → \"Hello\""),
    ("\"Hello\" + \" World\" = \"Hello World\"", "\"Hello\" + \" World\" = \"Hello World\""),
    ("Return \"Hello World\"", "Retourner \"Hello World\""),
    ("super() lets you build on the parent's implementation", "super() permet de s'appuyer sur l'implémentation du parent"),
    # Code comments to translate
    (" (list form)", " (forme liste)"),
    (" — C3 produces this ordering", " — C3 produit cet ordre"),
    (" — B comes first in MRO", " — B vient en premier dans le MRO"),
    ("in Python 2.3 (for new-style classes)", "dans Python 2.3 (pour les classes de nouveau style)"),
    ("A.__mro__ returns", "A.__mro__ retourne"),
    ("C(B) and B(A) form a linear inheritance chain", "C(B) et B(A) forment une chaîne d'héritage linéaire"),
    # More super(), cooperative init, mixins, etc.
    ("super() relies on knowing which class it's called from", "super() repose sur la connaissance de la classe d'où il est appelé"),
    ("and having a reference to the instance or class.", "et sur une référence à l'instance ou la classe."),
    ("Static methods provide neither.", "Les méthodes statiques ne fournissent ni l'un ni l'autre."),
    ("super() with no arguments uses compiler magic (__class__ and self/cls)", "super() sans arguments utilise la magie du compilateur (__class__ et self/cls)"),
    ("@staticmethod has no self or cls parameter", "@staticmethod n'a pas de paramètre self ni cls"),
    ("Without an instance or class, super() cannot determine the MRO position", "Sans instance ni classe, super() ne peut déterminer la position dans le MRO"),
    ("Calling super() in a staticmethod raises RuntimeError or TypeError", "Appeler super() dans une méthode statique lève RuntimeError ou TypeError"),
    ("In instance methods: super() uses __class__ (implicit) and self", "Dans les méthodes d'instance : super() utilise __class__ (implicite) et self"),
    ("In class methods: super() uses __class__ (implicit) and cls", "Dans les méthodes de classe : super() utilise __class__ (implicite) et cls"),
    ("In static methods: no self, no cls → super() fails", "Dans les méthodes statiques : pas de self, pas de cls → super() échoue"),
    ("You could use super(ClassName, instance) explicitly, but that defeats the purpose", "On pourrait utiliser super(ClassName, instance) explicitement, mais cela va à l'encontre du but"),
    ("The fix: don't use super() in static methods, or use @classmethod instead", "La solution : ne pas utiliser super() dans les méthodes statiques, ou utiliser @classmethod à la place"),
    ("Using super() is the recommended practice", "Utiliser super() est la pratique recommandée"),
    ("because it enables cooperative multiple inheritance and avoids hardcoding parent class names.", "car cela permet l'héritage multiple coopératif et évite de coder en dur les noms des classes parentes."),
    ("super().__init__() follows the MRO — correct for diamond inheritance", "super().__init__() suit le MRO — correct pour l'héritage en diamant"),
    ("ParentClass.__init__(self) hardcodes the parent — brittle, can cause double calls in diamonds", "ParentClass.__init__(self) code en dur le parent — fragile, peut causer des appels doubles dans les diamants"),
    ("super() adapts when the class hierarchy changes", "super() s'adapte quand la hiérarchie de classes change"),
    ("ParentClass.__init__(self) must be manually updated if inheritance changes", "ParentClass.__init__(self) doit être mis à jour manuellement si l'héritage change"),
    ("In a diamond (D → B → C → A), super().__init__() in B calls C.__init__ (MRO order)", "Dans un diamant (D → B → C → A), super().__init__() dans B appelle C.__init__ (ordre MRO)"),
    ("But B calling A.__init__(self) directly skips C entirely", "Mais B appelant A.__init__(self) directement saute C entièrement"),
    ("This can cause A.__init__ to run twice (once from B, once from C)", "Cela peut faire s'exécuter A.__init__ deux fois (une fois depuis B, une fois depuis C)"),
    ("super() prevents this by ensuring each __init__ runs exactly once", "super() évite cela en assurant que chaque __init__ s'exécute exactement une fois"),
    ("# BAD — hardcoded parent:", "# MAUVAIS — parent codé en dur :"),
    ("# GOOD — cooperative super():", "# BON — super() coopératif :"),
    ("Follows MRO correctly", "Suit le MRO correctement"),
    ("Breaks in diamond inheritance", "Casse dans l'héritage en diamant"),
]


def translate_text(text: str) -> str:
    """Apply header and phrase replacements."""
    result = text
    for eng, fr in HEADERS.items():
        result = result.replace(eng, fr)
    for eng, fr in PHRASES:
        result = result.replace(eng, fr)
    return result


def escape_for_ts(content: str) -> str:
    """Escape backticks and backslashes for TypeScript template literal."""
    return content.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def main():
    with open("scripts/extracted_2501_2650.json") as f:
        data = json.load(f)

    lines = [
        "/**",
        " * French translations for detailed explanations (IDs 2501-2650).",
        " * Ready to merge into DETAILED_EXPLANATIONS_FR.",
        " * Section headers: Concepts clés, Comment ça fonctionne, Exemple, Usages courants",
        " * Python code blocks preserved unchanged.",
        " */",
        "",
        "export const FR_2501_2650: Record<number, string> = {",
    ]

    for entry in data:
        eid = entry["id"]
        raw = entry["de"]
        translated = translate_text(raw)
        escaped = escape_for_ts(translated)
        lines.append(f'  {eid}: `{escaped}`,')

    lines.append("};")

    out_path = "scripts/fr_2501_2650_translations.ts"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written {len(data)} entries to {out_path}")


if __name__ == "__main__":
    main()
