// Generate French detailed explanations for IDs 2851-3000
// Run: npx tsx scripts/gen_fr_2851_3000.ts

import * as fs from "fs";

const data = JSON.parse(
  fs.readFileSync("scripts/q2851_3000.json", "utf-8")
) as Array<{ id: number; de: string }>;

const EN_FR: Record<string, string> = {
  "Key concepts:": "Concepts clés :",
  "How it works:": "Comment ça fonctionne :",
  "Example:": "Exemple :",
  "Common uses:": "Usages courants :",
  "Examples:": "Exemples :",
  "Workaround —": "Solution de contournement —",
  "Workaround:": "Solution de contournement :",
  "Problems with": "Problèmes avec",
  "The 19 principles include:": "Les 19 principes incluent :",
  " returns ": " renvoie ",
  " returns": " renvoie",
  "returns ": "renvoie ",
  " yields ": " produit ",
  "Yields ": "Produit ",
  " yields": " produit",
  " creates ": " crée ",
  " Creates ": " Crée ",
  " produces ": " produit ",
  "Produces ": "Produit ",
  " generates ": " génère ",
  "Generates ": "Génère ",
  " matches ": " correspond à ",
  "Matches ": "Correspond à ",
  " raises ": " lève ",
  "Raises ": "Lève ",
  " includes ": " inclut ",
  " includes": " inclut",
  " contains ": " contient ",
  "Contains ": "Contient ",
  " accepts ": " accepte ",
  "Accepts ": "Accepte ",
  " takes ": " prend ",
  "Takes ": "Prend ",
  " receives ": " reçoit ",
  " receives": " reçoit",
  " replaces ": " remplace ",
  "Replaces ": "Remplace ",
  " converts ": " convertit ",
  "Converts ": "Convertit ",
  " parses ": " parse ",
  "Parses ": "Parse ",
  " handles ": " gère ",
  "Handles ": "Gère ",
  " supports ": " prend en charge ",
  " Supports ": " Prend en charge ",
  " allows ": " permet ",
  "Allows ": "Permet ",
  " enables ": " permet ",
  "Enables ": "Permet ",
  " provides ": " fournit ",
  "Provides ": "Fournit ",
  " ensures ": " garantit ",
  "Ensures ": "Garantit ",
  " determines ": " détermine ",
  "Determines ": "Détermine ",
  " specifies ": " spécifie ",
  "Specifies ": "Spécifie ",
  " defines ": " définit ",
  "Defines ": "Définit ",
  " requires ": " requiert ",
  "Requires ": "Requiert ",
  " indicates ": " indique ",
  "Indicates ": "Indique ",
  " checks ": " vérifie ",
  "Checks ": "Vérifie ",
  " verifies ": " vérifie ",
  "Verifies ": "Vérifie ",
  " equivalent to ": " équivalent à ",
  "Equivalent to ": "Équivalent à ",
  "Equivalent to": "Équivalent à",
  " similar to ": " similaire à ",
  " Similar to ": " Similaire à ",
  " default ": " par défaut ",
  "Default ": "Par défaut ",
  " default": " par défaut",
  " optional ": " optionnel ",
  "Optional ": "Optionnel ",
  " first ": " premier ",
  "First ": "Premier ",
  " second ": " second ",
  "Second ": "Second ",
  " last ": " dernier ",
  "Last ": "Dernier ",
  " entire ": " entier ",
  "Entire ": "Entier ",
  " single ": " unique ",
  "Single ": "Unique ",
  " multiple ": " multiple ",
  "Multiple ": "Multiple ",
  " each ": " chaque ",
  "Each ": "Chaque ",
  " every ": " tout ",
  "Every ": "Tout ",
  " all ": " tous ",
  "All ": "Tous ",
  " both ": " les deux ",
  "Both ": "Les deux ",
  " only ": " seulement ",
  "Only ": "Seulement ",
  " when ": " quand ",
  "When ": "Quand ",
  " if ": " si ",
  "If ": "Si ",
  " unless ": " sauf si ",
  "Unless ": "Sauf si ",
  " until ": " jusqu'à ",
  "Until ": "Jusqu'à ",
  " before ": " avant ",
  "Before ": "Avant ",
  " after ": " après ",
  "After ": "Après ",
  " during ": " pendant ",
  "During ": "Pendant ",
  " without ": " sans ",
  "Without ": "Sans ",
  " with ": " avec ",
  "With ": "Avec ",
  " from ": " depuis ",
  "From ": "Depuis ",
  " to ": " vers ",
  "To ": "Vers ",
  " for ": " pour ",
  "For ": "Pour ",
  " and ": " et ",
  "And ": "Et ",
  " or ": " ou ",
  "Or ": "Ou ",
  " but ": " mais ",
  "But ": "Mais ",
  " not ": " pas ",
  "Not ": "Pas ",
  "Result:": "Résultat :",
  "Result ": "Résultat ",
  " result": " résultat",
  " result ": " résultat ",
  "Result": "Résultat",
  " elements": " éléments",
  " element": " élément",
  " values": " valeurs",
  " value": " valeur",
  " objects": " objets",
  " object": " objet",
  " strings": " chaînes",
  " string": " chaîne",
  " list": " liste",
  " list ": " liste ",
  " lists": " listes",
  " tuple": " tuple",
  " tuples": " tuples",
  " dictionary": " dictionnaire",
  " dictionaries": " dictionnaires",
  " function": " fonction",
  " functions": " fonctions",
  " method": " méthode",
  " methods": " méthodes",
  " parameter": " paramètre",
  " parameters": " paramètres",
  " argument": " argument",
  " arguments": " arguments",
  " exception": " exception",
  " exceptions": " exceptions",
  " error": " erreur",
  " errors": " erreurs",
  " file": " fichier",
  " files": " fichiers",
  " key": " clé",
  " keys": " clés",
  " number": " nombre",
  " numbers": " nombres",
  " character": " caractère",
  " characters": " caractères",
  " line": " ligne",
  " lines": " lignes",
  " level": " niveau",
  " levels": " niveaux",
  " message": " message",
  " messages": " messages",
  " output": " sortie",
  " input": " entrée",
  " returns": " renvoie",
  "Stops at the shortest": "S'arrête au plus court",
  "Stops when": "S'arrête quand",
  "Must be limited": "Doit être limité",
  "Must be called": "Doit être appelé",
  "Cannot be used": "Ne peut pas être utilisé",
  "Can only be used": "Ne peut être utilisé que",
  "Works with": "Fonctionne avec",
  "Works on": "Fonctionne sur",
  "Works like": "Fonctionne comme",
  "Equivalent to": "Équivalent à",
  "Unlike ": "Contrairement à ",
  "Unlike regular": "Contrairement aux",
  "Similar to": "Similaire à",
  "Same as": "Identique à",
  "Different from": "Différent de",
  "Instead of": "Au lieu de",
  "Rather than": "Plutôt que",
  "As opposed to": "Par opposition à",
  "By default": "Par défaut",
  "By default,": "Par défaut,",
  "In Python": "En Python",
  "In Python,": "En Python,",
  "In Python ": "En Python ",
};

function translate(t: string): string {
  let out = t;
  for (const [en, fr] of Object.entries(EN_FR)) {
    out = out.split(en).join(fr);
  }
  return out;
}

const lines: string[] = [];
for (const item of data) {
  const translated = translate(item.de);
  const escaped = translated.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  lines.push(`  ${item.id}: \`${escaped}\`,`);
}

const block = "  // IDs 2851-3000: re, itertools, json, pathlib, logging, unittest, exceptions, PEP 8, asyncio, Pythonic\n" + lines.join("\n");
fs.writeFileSync("scripts/fr_detailed_2851_3000.ts", block);
console.log("Wrote scripts/fr_detailed_2851_3000.ts");
